on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

env:
  CGO_ENABLED: 0

jobs:
  release-linux-amd64:
    name: release multi-platform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.RELEASER_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: bgmi-renamer
        compress_assets: OFF
        md5sum: FALSE
